import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

type Props = {
	page: string;
};

const Layout: React.FC<Props> = ({ children, page = 'home' }) => {
	return (
		<>
			<Head>
				<title>Space project</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className='primary-header flex'>
				<Link href='/'>
					<a>
						<>
							<span className='sr-only'>Homepage</span>
							<Image
								src='/assets/shared/logo.svg'
								alt='space tourism logo'
								className='logo'
								width='48'
								height='48'
							/>
						</>
					</a>
				</Link>
				<button
					className='mobile-nav-toggle'
					aria-controls='primary-navigation'
					aria-expanded='false'
				>
					<span className='sr-only'>Menu</span>
				</button>
				<nav>
					<ul
						id='primary-navigation'
						data-visible='false'
						className='primary-navigation underline-indicators flex'
					>
						<li className='active'>
							<Link href='/'>
								<a
									className='
								uppercase
								text-white
								ff-sans-cond
								letter-spacing-2
							'
								>
									<span aria-hidden='true'>00</span> Home
								</a>
							</Link>
						</li>
						<li>
							<Link href='/destination'>
								<a
									className='
								uppercase
								text-white
								ff-sans-cond
								letter-spacing-2
							'
								>
									<span aria-hidden='true'>01</span>{' '}
									Destination
								</a>
							</Link>
						</li>
						<li>
							<Link href='/crew'>
								<a
									className='
								uppercase
								text-white
								ff-sans-cond
								letter-spacing-2
							'
								>
									<span aria-hidden='true'>02</span> Crew
								</a>
							</Link>
						</li>
						<li>
							<Link href='/technology'>
								<a
									className='
								uppercase
								text-white
								ff-sans-cond
								letter-spacing-2
							'
								>
									<span aria-hidden='true'>03</span>{' '}
									Technology
								</a>
							</Link>
						</li>
					</ul>
				</nav>
			</header>

			<main
				id='main'
				className={`grid-container grid-container--${page}`}
			>
				{children}
			</main>

			<footer className='footer'>
				<div className='attribution letter-spacing-3 text-white'>
					Challenge by
					<a
						className='text-accent'
						href='https://www.frontendmentor.io?ref=challenge'
						target='_blank'
						rel='noreferrer'
					>
						Frontend Mentor
					</a>
					. Coded by{' '}
					<a href='#' className='text-accent'>
						Thomas Jonstrup
					</a>
					.
				</div>
			</footer>
		</>
	);
};

export default Layout;
