import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Nav from './Nav';

type Props = {
	page: string;
	extraClassName?: string;
};

const Layout: React.FC<Props> = ({
	children,
	page = 'home',
	extraClassName,
}) => {
	const [openMenu, setOpenMenu] = useState(false);

	useEffect(() => {
		document.body.className = page;
	}, [page]);

	let mainClassNames: string = `grid-container grid-container--${page}`;

	if (extraClassName) {
		mainClassNames += ` ${extraClassName}`;
	}

	const handleClick = () => {
		setOpenMenu(!openMenu);
	};

	return (
		<>
			<Head>
				<title>Space project</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className='primary-header flex'>
				<Link href='/'>
					<a>
						<>
							<span className='sr-only'>Homepage</span>
							{/* 						<Image
								src='/assets/shared/logo.svg'
								alt='space tourism logo'
								className='logo'
								width='48'
								height='48'
							/> */}
							<img
								src='/assets/shared/logo.svg'
								alt='space tourism logo'
								className='logo'
							/>
						</>
					</a>
				</Link>
				<button
					className={
						openMenu
							? 'mobile-nav-toggle mobile-nav-toggle--close'
							: 'mobile-nav-toggle'
					}
					aria-controls='primary-navigation'
					aria-expanded={openMenu}
					onClick={handleClick}
				>
					<span className='sr-only'>Menu</span>
				</button>
				<Nav openMobile={openMenu} />
			</header>

			<main id='main' className={mainClassNames}>
				{children}
			</main>

			<footer className='footer'>
				<div className='attribution letter-spacing-3 text-white'>
					Challenge by
					<a
						className='text-accent'
						href='https://www.frontendmentor.io?ref=challenge'
						target='_blank'
						rel='noreferrer'
					>
						Frontend Mentor
					</a>
					. Coded by{' '}
					<a href='#' className='text-accent'>
						Thomas Jonstrup
					</a>
					.
				</div>
			</footer>
		</>
	);
};

export default Layout;
